### ISSUE TITLE
Wheel missing on PyPI

### ISSUE THREAD

**Issue by fabiogra** [andfanilo/streamlit-css-button#2]
Hello @andfanilo ,

I'm interested in personalize buttons in a streamlit app and I found this nice project, is it still maintained? I tried to install it with
`pip install streamlit-css-button` but no matching distribution found for streamlit-css-button.

**Comment by andfanilo** [comment]
Hey!
So I haven't pushed this on PyPi because unfortunately it's still a little bit buggy when there are multiple of those buttons, because the click of a button provokes a click of others :/
I'm waiting for https://github.com/streamlit/streamlit/issues/2555 or https://github.com/streamlit/streamlit/issues/3977 to go back to this component...
If you feel courageous you can build it yourself by replacing `npm run dev` by `npm run build` and you shouldn't have to run the dev server again
Have a nice day
Fanilo
